drop user TEST_XA1 cascade
/
drop user TEST_XA2 cascade
/

CREATE USER TEST_XA1 IDENTIFIED BY TEST_XA1
DEFAULT TABLESPACE "MY_TEST"
TEMPORARY TABLESPACE "TEMP"
/

-- ROLES
GRANT "CONNECT" TO TEST_XA1
/
ALTER USER TEST_XA1 DEFAULT ROLE "CONNECT"
/
-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO TEST_XA1
/
GRANT DEBUG CONNECT SESSION TO TEST_XA1
/
GRANT CREATE SEQUENCE TO TEST_XA1
/
GRANT CREATE TABLE TO TEST_XA1
/
GRANT CREATE VIEW TO TEST_XA1
/
GRANT CREATE SESSION TO TEST_XA1
/
GRANT CREATE MATERIALIZED VIEW TO TEST_XA1
/
GRANT DEBUG ANY PROCEDURE TO TEST_XA1
/
GRANT  SELECT ANY TABLE to TEST_XA1
/
ALTER USER TEST_XA1 QUOTA 200M ON MY_TEST
/
GRANT UNLIMITED TABLESPACE TO TEST_XA1
/
--another schema -- may be created in another database server too!
CREATE USER TEST_XA2 IDENTIFIED BY TEST_XA2
DEFAULT TABLESPACE "MY_TEST"
TEMPORARY TABLESPACE "TEMP"
/

-- ROLES
GRANT "CONNECT" TO TEST_XA2
/
ALTER USER TEST_XA2 DEFAULT ROLE "CONNECT"
/
-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO TEST_XA2
/
GRANT DEBUG CONNECT SESSION TO TEST_XA2
/
GRANT CREATE SEQUENCE TO TEST_XA2
/
GRANT CREATE TABLE TO TEST_XA2
/
GRANT CREATE VIEW TO TEST_XA2
/
GRANT CREATE SESSION TO TEST_XA2
/
GRANT CREATE MATERIALIZED VIEW TO TEST_XA2
/
GRANT DEBUG ANY PROCEDURE TO TEST_XA2
/
GRANT  SELECT ANY TABLE to TEST_XA2
/
ALTER USER TEST_XA2 QUOTA 200M ON MY_TEST
/
GRANT UNLIMITED TABLESPACE TO TEST_XA2
/


--create table in the TEST_XA1 schema
create table testjta1 (
my_id NUMBER primary key,
key VARCHAR2(300) not null,
value VARCHAR2(300) not null
)
/

--create table in the TEST_XA2 schema
create table testjta2 (
my_id NUMBER primary key,
key VARCHAR2(300) not null,
value VARCHAR2(300) not null
)
/
